FROM php:8.2-apache

ARG TMZN=Europe/Berlin

WORKDIR /var/www/html/word-app/api

RUN apt-get update && apt-get install -y vim libmariadb-dev tzdata
RUN ln -snf /usr/share/zoneinfo/$TMZN /etc/localtime && echo $TMZN > /etc/timezone
RUN docker-php-ext-install pdo pdo_mysql
RUN a2enmod headers
RUN echo "<IfModule mod_headers.c>\n\
Header set Access-Control-Allow-Origin \"*\"\n\
Header set Access-Control-Allow-Methods \"GET, POST, PUT, DELETE, OPTIONS\"\n\
Header set Access-Control-Allow-Headers \"Content-Type, Authorization\"\n\
Header set Access-Control-Allow-Credentials \"true\"\n\
</IfModule>" >> /etc/apache2/apache2.conf
RUN a2enmod rewrite
RUN echo "ServerName localhost" >> /etc/apache2/conf-available/servername.conf && \
    a2enconf servername

EXPOSE 80

CMD ["apache2-foreground"]